{{
  config(
    materialized = 'ephemeral',
  )
}}


WITH T_LISTING AS (
SELECT *
FROM {{ref ('T_LISTING')}}

)

SELECT 
    LISTING_ID,
    LISTING_URL,
    LISTING_NAME,
    ROOM_TYPE,
    CASE WHEN MINIMUM_NIGHTS = 0 THEN  1 ELSE MINIMUM_NIGHTS END AS MINIMUM_NIGHTS,
    HOST_ID,
    CAST(REPLACE(PRICE_STR, '$', ' ') AS FLOAT) AS PRICE,
    CREATED_AT,
    UPDATED_AT

FROM T_LISTING 
