WITH RAW_LISTING AS (
    SELECT * FROM {{ ref('T_LISTING') }}
)

SELECT 
   LISTING_ID,
   LISTING_URL,
   LISTING_NAME,
   ROOM_TYPE,
   CASE WHEN MINIMUM_NIGHTS = 0 THEN  1 ELSE MINIMUM_NIGHTS END AS MINIMUM_NIGHTS,
   HOST_ID,
   CAST(REPLACE(PRICE, '$', ' ') AS FLOAT) AS PRICE,
   CREATED_AT,
   UPDATED_AT
FROM RAW_LISTING

