WITH RAW_LISTING AS (
    SELECT * FROM {{ ref('T_LISTING') }}
), LISTING AS (

SELECT 
   LISTING_ID,
   LISTING_URL,
   LISTING_NAME,
   ROOM_TYPE,
   CASE WHEN MINIMUM_NIGHTS = 0 THEN  1 ELSE MINIMUM_NIGHTS END AS MINIMUM_NIGHTS,
   HOST_ID,
   CAST(REPLACE(PRICE, '$', ' ') AS FLOAT) AS PRICE,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY CAST(REPLACE(PRICE, '$', ' ') AS FLOAT)) OVER () AS p25,
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY CAST(REPLACE(PRICE, '$', ' ') AS FLOAT)) OVER () AS p75,
        PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY CAST(REPLACE(PRICE, '$', ' ') AS FLOAT)) OVER () AS p99,
   CREATED_AT,
   UPDATED_AT
FROM RAW_LISTING
)

SELECT * EXCLUDE (p25, p75, p99),
    CASE
        WHEN PRICE <= p25 THEN 'Bottom 25%'
        WHEN PRICE <= p75 THEN '25-75%'
        WHEN PRICE <= p99 THEN '75-99%'
        ELSE 'Top 1%'
    END AS PRICE_CATEGORY
FROM LISTING

