{{
    config(
        materialized = 'table'
    )
    
    }}


WITH H AS (
    SELECT * FROM {{ref('DIM_HOSTS')}}
),
L AS (
    SELECT * FROM {{ref('DIM_LISTINGS')}}
)
SELECT 
    L.LISTING_ID,
    H.HOST_ID,
    H.HOST_NAME,
    H.IS_SUPERHOST,
    L.LISTING_URL,
    L.LISTING_NAME,
    L.ROOM_TYPE,
    L.PRICE,
    L.PRICE_CATEGORY,
    GREATEST(H.CREATED_AT, L.CREATED_AT) AS CREATED_AT,
    GREATEST(H.UPDATED_AT, L.UPDATED_AT) AS UPDATED_AT

FROM L 
LEFT JOIN H
ON L.HOST_ID = H.HOST_ID