WITH RAW_HOSTS AS (
    SELECT * FROM {{ ref ('T_HOSTS') }}
)


SELECT
    HOST_ID ,
    COALESCE(HOST_NAME, 'Anonymous') AS HOST_NAME,
    COALESCE(IS_SUPERHOST,'NA') AS IS_SUPERHOST,
    CREATED_AT,
    UPDATED_AT
FROM RAW_HOSTS
