WITH RAW_REVIEWS AS (
    SELECT *
    FROM {{ source('airbnb', 'reviews') }}
)

SELECT 
    LISTING_ID,
    DATE AS REVIEW_DATE,
    REVIEWER_NAME AS REVIEWER_NAME,
    comments AS REVIEW_TEXT,
    COALESCE(sentiment,'NA') AS REVIEW_SENTIMENT
FROM RAW_REVIEWS
WHERE REVIEW_TEXT IS NOT NULL
  AND REVIEW_TEXT <> ''
